// Code generated by "stringer -type=SunType"; DO NOT EDIT.

package suntype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Full-1]
	_ = x[Partial-2]
	_ = x[Shade-3]
}

const _SunType_name = "UnknownFullPartialShade"

var _SunType_index = [...]uint8{0, 7, 11, 18, 23}

func (i SunType) String() string {
	if i < 0 || i >= SunType(len(_SunType_index)-1) {
		return "SunType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SunType_name[_SunType_index[i]:_SunType_index[i+1]]
}
