// Code generated by "stringer -type=PlantFamily"; DO NOT EDIT.

package plantfamily

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Adoxaceae-1]
	_ = x[Allium-2]
	_ = x[Amaranthaceae-3]
	_ = x[Apiaceae-4]
	_ = x[Apocynaceae-5]
	_ = x[Asparagaceae-6]
	_ = x[Asteraceae-7]
	_ = x[Boraginaceae-8]
	_ = x[Brassicaceae-9]
	_ = x[Campanulaceae-10]
	_ = x[Caprifoliaceae-11]
	_ = x[Caryophyllaceae-12]
	_ = x[Convolvulaceae-13]
	_ = x[Cucurbitaceae-14]
	_ = x[Fabaceae-15]
	_ = x[Lamiaceae-16]
	_ = x[Linaceae-17]
	_ = x[Malvaceae-18]
	_ = x[Onagraceae-19]
	_ = x[Papaveraceae-20]
	_ = x[Poaceae-21]
	_ = x[Polygonaceae-22]
	_ = x[Ranunculaceae-23]
	_ = x[Rosaceae-24]
	_ = x[Solanaceae-25]
	_ = x[Tropaeolaceae-26]
	_ = x[Violaceae-27]
	_ = x[Wildflower-28]
}

const _PlantFamily_name = "UnknownAdoxaceaeAlliumAmaranthaceaeApiaceaeApocynaceaeAsparagaceaeAsteraceaeBoraginaceaeBrassicaceaeCampanulaceaeCaprifoliaceaeCaryophyllaceaeConvolvulaceaeCucurbitaceaeFabaceaeLamiaceaeLinaceaeMalvaceaeOnagraceaePapaveraceaePoaceaePolygonaceaeRanunculaceaeRosaceaeSolanaceaeTropaeolaceaeViolaceaeWildflower"

var _PlantFamily_index = [...]uint16{0, 7, 16, 22, 35, 43, 54, 66, 76, 88, 100, 113, 127, 142, 156, 169, 177, 186, 194, 203, 213, 225, 232, 244, 257, 265, 275, 288, 297, 307}

func (i PlantFamily) String() string {
	if i < 0 || i >= PlantFamily(len(_PlantFamily_index)-1) {
		return "PlantFamily(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlantFamily_name[_PlantFamily_index[i]:_PlantFamily_index[i+1]]
}
