// Code generated by "stringer -type=SoilType"; DO NOT EDIT.

package soiltype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Dry-1]
	_ = x[Wet-2]
	_ = x[Both-3]
}

const _SoilType_name = "UnknownDryWetBoth"

var _SoilType_index = [...]uint8{0, 7, 10, 13, 17}

func (i SoilType) String() string {
	if i < 0 || i >= SoilType(len(_SoilType_index)-1) {
		return "SoilType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SoilType_name[_SoilType_index[i]:_SoilType_index[i+1]]
}
