# Generated by Django 4.1.7 on 2023-02-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxinventory', '0002_alter_box_options_alter_boxcontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='want_qr',
            field=models.BooleanField(default=False, verbose_name='QR code?'),
        ),
    ]
