# Generated by Django 4.1.7 on 2023-02-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxinventory', '0003_alter_box_want_qr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['name'], 'verbose_name_plural': 'boxes'},
        ),
    ]
