# Generated by Django 4.1.7 on 2023-05-06 20:07

import datetime
from django.db import migrations, models

def move_dates(apps, schema_editor):
    BoxContent = apps.get_model('boxinventory', 'BoxContent')
    for bc in BoxContent.objects.all():
        d = datetime.date(bc.when_planted, 1, 1)
        bc.planted = d
        bc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('boxinventory', '0004_alter_box_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxcontent',
            name='planted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterModelOptions(
            name='boxcontent',
            options={'ordering': ['planted', 'name']},
        ),
        migrations.RunPython(move_dates),
        migrations.RemoveField(
            model_name='boxcontent',
            name='when_planted',
        ),
    ]
