# Generated by Django 4.1.7 on 2023-05-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxinventory', '0005_alter_boxcontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='qr_applied',
            field=models.BooleanField(default=False, verbose_name='QR code applied?'),
        ),
    ]
