# Generated by Django 4.1.7 on 2023-05-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxinventory', '0006_box_qr_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxcontent',
            name='removed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
