// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"

	"go.universe.tf/garden/gogarden/types"
)

type HerbariumFamily struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type HerbariumPlant struct {
	ID               int64        `json:"id"`
	Edible           sql.NullBool `json:"edible"`
	NeedsTrellis     sql.NullBool `json:"needs_trellis"`
	NeedsBirdNetting sql.NullBool `json:"needs_bird_netting"`
	IsKeto           sql.NullBool `json:"is_keto"`
	Native           sql.NullBool `json:"native"`
	Invasive         sql.NullBool `json:"invasive"`
	IsCover          sql.NullBool `json:"is_cover"`
	GrowFromSeed     sql.NullBool `json:"grow_from_seed"`
	Type             string       `json:"type"`
	Lifespan         string       `json:"lifespan"`
	BadForCats       sql.NullBool `json:"bad_for_cats"`
	DeerResistant    sql.NullBool `json:"deer_resistant"`
	FamilyID         int64        `json:"family_id"`
	Name             string       `json:"name"`
}

type HerbariumPlantTag struct {
	ID      int64 `json:"id"`
	PlantID int64 `json:"plant_id"`
	TagID   int64 `json:"tag_id"`
}

type HerbariumPlantingwindow struct {
	ID      int64  `json:"id"`
	Type    string `json:"type"`
	End     int64  `json:"end"`
	Start   int64  `json:"start"`
	PlantID int64  `json:"plant_id"`
}

type HerbariumPlantname struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	PlantID int64  `json:"plant_id"`
}

type HerbariumTag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Location struct {
	ID      int64         `json:"id"`
	Name    string        `json:"name"`
	QRState types.QRState `json:"qr_state"`
}

type Planted struct {
	ID       int64      `json:"id"`
	Name     string     `json:"name"`
	Location int64      `json:"location"`
	Planted  types.Time `json:"planted"`
	Removed  types.Time `json:"removed"`
}
