// Code generated by "stringer -type=QRState"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Missing-0]
	_ = x[Applied-1]
	_ = x[Ignore-2]
}

const _QRState_name = "MissingAppliedIgnore"

var _QRState_index = [...]uint8{0, 7, 14, 20}

func (i QRState) String() string {
	if i < 0 || i >= QRState(len(_QRState_index)-1) {
		return "QRState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QRState_name[_QRState_index[i]:_QRState_index[i+1]]
}
