// Code generated by "stringer -type=PlantLifespan"; DO NOT EDIT.

package plantlifespan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Annual-1]
	_ = x[Perennial-2]
}

const _PlantLifespan_name = "UnknownAnnualPerennial"

var _PlantLifespan_index = [...]uint8{0, 7, 13, 22}

func (i PlantLifespan) String() string {
	if i < 0 || i >= PlantLifespan(len(_PlantLifespan_index)-1) {
		return "PlantLifespan(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlantLifespan_name[_PlantLifespan_index[i]:_PlantLifespan_index[i+1]]
}
