// Code generated by "stringer -type=PlantFamily -trimprefix=PlantFamily"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlantFamilyUnknown-0]
	_ = x[PlantFamilyAdoxaceae-1]
	_ = x[PlantFamilyAllium-2]
	_ = x[PlantFamilyAmaranthaceae-3]
	_ = x[PlantFamilyApiaceae-4]
	_ = x[PlantFamilyApocynaceae-5]
	_ = x[PlantFamilyAsparagaceae-6]
	_ = x[PlantFamilyAsteraceae-7]
	_ = x[PlantFamilyBoraginaceae-8]
	_ = x[PlantFamilyBrassicaceae-9]
	_ = x[PlantFamilyCampanulaceae-10]
	_ = x[PlantFamilyCaprifoliaceae-11]
	_ = x[PlantFamilyCaryophyllaceae-12]
	_ = x[PlantFamilyConvolvulaceae-13]
	_ = x[PlantFamilyCucurbitaceae-14]
	_ = x[PlantFamilyFabaceae-15]
	_ = x[PlantFamilyLamiaceae-16]
	_ = x[PlantFamilyLinaceae-17]
	_ = x[PlantFamilyMalvaceae-18]
	_ = x[PlantFamilyOnagraceae-19]
	_ = x[PlantFamilyPapaveraceae-20]
	_ = x[PlantFamilyPoaceae-21]
	_ = x[PlantFamilyPolygonaceae-22]
	_ = x[PlantFamilyRanunculaceae-23]
	_ = x[PlantFamilyRosaceae-24]
	_ = x[PlantFamilySolanaceae-25]
	_ = x[PlantFamilyTropaeolaceae-26]
	_ = x[PlantFamilyViolaceae-27]
	_ = x[PlantFamilyWildflower-28]
}

const _PlantFamily_name = "UnknownAdoxaceaeAlliumAmaranthaceaeApiaceaeApocynaceaeAsparagaceaeAsteraceaeBoraginaceaeBrassicaceaeCampanulaceaeCaprifoliaceaeCaryophyllaceaeConvolvulaceaeCucurbitaceaeFabaceaeLamiaceaeLinaceaeMalvaceaeOnagraceaePapaveraceaePoaceaePolygonaceaeRanunculaceaeRosaceaeSolanaceaeTropaeolaceaeViolaceaeWildflower"

var _PlantFamily_index = [...]uint16{0, 7, 16, 22, 35, 43, 54, 66, 76, 88, 100, 113, 127, 142, 156, 169, 177, 186, 194, 203, 213, 225, 232, 244, 257, 265, 275, 288, 297, 307}

func (i PlantFamily) String() string {
	if i < 0 || i >= PlantFamily(len(_PlantFamily_index)-1) {
		return "PlantFamily(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlantFamily_name[_PlantFamily_index[i]:_PlantFamily_index[i+1]]
}
