// Code generated by "stringer -type=QRState -trimprefix=QRState"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QRStateWant-0]
	_ = x[QRStateApplied-1]
	_ = x[QRStateIgnore-2]
	_ = x[QRStateUnknown-3]
}

const _QRState_name = "WantAppliedIgnoreUnknown"

var _QRState_index = [...]uint8{0, 4, 11, 17, 24}

func (i QRState) String() string {
	if i < 0 || i >= QRState(len(_QRState_index)-1) {
		return "QRState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QRState_name[_QRState_index[i]:_QRState_index[i+1]]
}
