// Code generated by "stringer -type=Tribool -trimprefix=Tribool"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TriboolUnknown-0]
	_ = x[TriboolTrue-1]
	_ = x[TriboolFalse-2]
}

const _Tribool_name = "UnknownTrueFalse"

var _Tribool_index = [...]uint8{0, 7, 11, 16}

func (i Tribool) String() string {
	if i < 0 || i >= Tribool(len(_Tribool_index)-1) {
		return "Tribool(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tribool_name[_Tribool_index[i]:_Tribool_index[i+1]]
}
