# Generated by Django 4.1.7 on 2023-02-27 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'families',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edible', models.BooleanField(default=False, verbose_name='Edible?')),
                ('needs_trellis', models.BooleanField(default=False, verbose_name='Needs trellis?')),
                ('needs_bird_netting', models.BooleanField(default=False, verbose_name='Needs bird netting?')),
                ('is_keto', models.BooleanField(default=False, verbose_name='Is keto?')),
                ('native', models.BooleanField(default=False, verbose_name='Native plant?')),
                ('invasive', models.BooleanField(default=False, verbose_name='Is invasive?')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Cover crop?')),
                ('grow_from_seed', models.BooleanField(default=True, verbose_name='Good to grow from seeds?')),
                ('type', models.CharField(choices=[('V', 'Vegetable'), ('F', 'Fruit'), ('H', 'Herb'), ('L', 'Flower'), ('G', 'Green')], max_length=1)),
                ('lifespan', models.CharField(choices=[('A', 'Annual'), ('B', 'Biennial'), ('P', 'Perennial')], max_length=1)),
                ('bad_for_cats', models.BooleanField(default=False, verbose_name='Bad for cats?')),
                ('deer_resistant', models.BooleanField(default=False, verbose_name='Deer resistant?')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbarium.family')),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('heat_sensitive', models.BooleanField(default=False, verbose_name='Cover during heatwaves?')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbarium.plant')),
            ],
            options={
                'verbose_name_plural': 'varieties',
            },
        ),
        migrations.CreateModel(
            name='PlantName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbarium.plant')),
            ],
            options={
                'verbose_name_plural': 'plant names',
            },
        ),
    ]
