# Generated by Django 4.1.7 on 2023-02-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='edible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variety',
            name='invasive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variety',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variety',
            name='is_keto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variety',
            name='native',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variety',
            name='needs_bird_netting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variety',
            name='needs_trellis',
            field=models.BooleanField(default=False),
        ),
    ]
