# Generated by Django 4.1.7 on 2023-02-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='bad_for_cats',
            field=models.BooleanField(null=True, verbose_name='Bad for cats?'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='deer_resistant',
            field=models.BooleanField(null=True, verbose_name='Deer resistant?'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='edible',
            field=models.BooleanField(null=True, verbose_name='Edible?'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='grow_from_seed',
            field=models.BooleanField(default=True, null=True, verbose_name='Good to grow from seeds?'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='invasive',
            field=models.BooleanField(null=True, verbose_name='Is invasive?'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='is_cover',
            field=models.BooleanField(null=True, verbose_name='Cover crop?'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='is_keto',
            field=models.BooleanField(null=True, verbose_name='Is keto?'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='lifespan',
            field=models.CharField(choices=[('A', 'Annual'), ('B', 'Biennial'), ('P', 'Perennial'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='native',
            field=models.BooleanField(null=True, verbose_name='Native plant?'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='needs_bird_netting',
            field=models.BooleanField(null=True, verbose_name='Needs bird netting?'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='needs_trellis',
            field=models.BooleanField(null=True, verbose_name='Needs trellis?'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='heat_sensitive',
            field=models.BooleanField(null=True, verbose_name='Cover during heatwaves?'),
        ),
    ]
