# Generated by Django 4.1.7 on 2023-02-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0002_alter_plant_bad_for_cats_alter_plant_deer_resistant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name'], 'verbose_name_plural': 'families'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'ordering': ['name'], 'verbose_name_plural': 'varieties'},
        ),
    ]
