# Generated by Django 4.1.7 on 2023-02-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0003_alter_family_options_alter_variety_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
