# Generated by Django 4.1.7 on 2023-02-28 07:48

from django.db import migrations

def primary_name(apps, schema_editor):
    Plant = apps.get_model('herbarium', 'Plant')
    PlantName = apps.get_model('herbarium', 'PlantName')
    for p in Plant.objects.all():
        names = p.plantname_set.all()
        if names:
            p.name = names[0].name
            p.save()
            names[0].delete()

class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0004_plant_name'),
    ]

    operations = [
        migrations.RunPython(primary_name),
    ]
