# Generated by Django 4.1.7 on 2023-02-28 05:59

from django.db import migrations

def merge_varieties(apps, schema_editor):
    Plant = apps.get_model('herbarium', 'Plant')
    PlantName = apps.get_model('herbarium', 'PlantName')
    Variety = apps.get_model('herbarium', 'Variety')
    old_plants = set()
    for var in Variety.objects.all():
        old_plants.add(var.plant)
        print('making new plant for {} ({}, {})'.format(var.name, var.id, var.plant_id))
        new_plant = Plant(name='{} ({})'.format(var.plant.name, var.name),
                          family=var.plant.family,
                          edible=var.plant.edible,
                          needs_trellis=var.plant.needs_trellis,
                          needs_bird_netting=var.plant.needs_bird_netting,
                          is_keto=var.plant.is_keto,
                          native=var.plant.native,
                          invasive=var.plant.invasive,
                          is_cover=var.plant.is_cover,
                          grow_from_seed=var.plant.grow_from_seed,
                          type=var.plant.type,
                          lifespan=var.plant.lifespan,
                          bad_for_cats=var.plant.bad_for_cats,
                          deer_resistant=var.plant.deer_resistant)
        new_plant.save()
        for n in var.plant.plantname_set.all():
            PlantName(name=n, plant=new_plant).save()
        var.delete()
    for p in old_plants:
        p.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0006_alter_plant_options'),
    ]

    operations = [
        migrations.RunPython(merge_varieties),
    ]
