# Generated by Django 4.1.7 on 2023-03-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0007_merge_variants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variety',
        ),
    ]
