# Generated by Django 4.1.7 on 2023-03-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium', '0008_delete_variety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='tags',
            field=models.ManyToManyField(to='herbarium.tag'),
        ),
    ]
